-- Snowflake database and schema draft for later phases

CREATE DATABASE IF NOT EXISTS BANKING_DW;

CREATE SCHEMA IF NOT EXISTS BANKING_DW.BRONZE;
CREATE SCHEMA IF NOT EXISTS BANKING_DW.SILVER;
CREATE SCHEMA IF NOT EXISTS BANKING_DW.GOLD;
CREATE SCHEMA IF NOT EXISTS BANKING_DW.AUDIT;
