-- Snowflake Setup

CREATE DATABASE IF NOT EXISTS FINLAKE_ANALYTICS;

CREATE SCHEMA IF NOT EXISTS FINLAKE_ANALYTICS.GOLD;

CREATE WAREHOUSE IF NOT EXISTS FINLAKE_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE;

USE DATABASE FINLAKE_ANALYTICS;
USE SCHEMA GOLD;
USE WAREHOUSE FINLAKE_WH;

-- After Databricks load, run checks:

SELECT 'GOLD_CUSTOMER_LOAN_SUMMARY' AS table_name, COUNT(*) AS row_count
FROM FINLAKE_ANALYTICS.GOLD.GOLD_CUSTOMER_LOAN_SUMMARY
UNION ALL
SELECT 'GOLD_BRANCH_PERFORMANCE_SUMMARY', COUNT(*)
FROM FINLAKE_ANALYTICS.GOLD.GOLD_BRANCH_PERFORMANCE_SUMMARY
UNION ALL
SELECT 'GOLD_MONTHLY_COLLECTION_SUMMARY', COUNT(*)
FROM FINLAKE_ANALYTICS.GOLD.GOLD_MONTHLY_COLLECTION_SUMMARY
UNION ALL
SELECT 'GOLD_LOAN_DEFAULT_RISK_SUMMARY', COUNT(*)
FROM FINLAKE_ANALYTICS.GOLD.GOLD_LOAN_DEFAULT_RISK_SUMMARY
UNION ALL
SELECT 'GOLD_PORTFOLIO_KPIS', COUNT(*)
FROM FINLAKE_ANALYTICS.GOLD.GOLD_PORTFOLIO_KPIS;
