USE DATABASE FINLAKE_ANALYTICS;
SHOW SCHEMAS;
SHOW OBJECTS IN SCHEMA FINLAKE_ANALYTICS.DBT_STAGING;
SHOW OBJECTS IN SCHEMA FINLAKE_ANALYTICS.DBT_MARTS;

SELECT *
FROM FINLAKE_ANALYTICS.DBT_MARTS.MART_HIGH_RISK_LOANS
ORDER BY RISK_SCORE DESC, TOTAL_OVERDUE_AMOUNT DESC
LIMIT 20;

SELECT *
FROM FINLAKE_ANALYTICS.DBT_MARTS.MART_BRANCH_RISK_DASHBOARD
ORDER BY TOTAL_DISBURSED_AMOUNT DESC;

SELECT *
FROM FINLAKE_ANALYTICS.DBT_MARTS.MART_PORTFOLIO_EXECUTIVE_SUMMARY;
